openchange/openchange

mapiproxy/libmapistore/backends/python/rest.py, mapiproxy/libmapistore/mapistore_python.c, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcmsg.c
* ` 54e7efd` includes small modifications in _rest.py_ that improve the semantics around `message_save` (e.g. folder permissions, restrictions, etc.). Message double-save is still not possible in OL.
* `6646bef` wraps in a method the way binary properties are encoded/decoded in order to push/retrieve them from/to the server
* `c52381e` includes various small fixes in _rest.py_
* `be58fac` implements the `RopModifyRecipients` operation in the REST API backend. The way recipients are pushed to the server (as a property) should be discussed. For instance, if we pass them as a property of the message dictionaries, maybe they could also be part of the message properties in _rest.py_ and not a separate attribute of message objects (in that case, `get_message_data` in _mapistore_python.c_ should …
=> Include modify_recipients

mapiproxy/libmapiproxy/backends/openchangedb_mysql.c, testsuite/libmapiproxy/openchangedb.c, testsuite/libmapiproxy/openchangedb_logger.c
Now *set properties* works when setting a row with some of the *handled* properties
=> Fix message set properties from openchangedb

mapiproxy/libmapistore/backends/python/rest.py, mapiproxy/libmapistore/mapistore_python.c, python/mock/rest/api_server.py
This PR implements the submit operation for E-mails in mapistore_python.c and rest.py. The latter doesn't check the return value of the server, which at this moment only takes the parameters (the message properties+recipients and the flag that indicates if any processing is needed).
The method doesn't check the permissions either, nor it modifies any properties apart from `PidTagClientSubmitTime`.
=> Include submit_message

libmapi/idset.c, libmapi/libmapi.h, mapiproxy/servers/default/emsmdb/oxcfxics.c
Two fixes there as explained in the commit messages:
* Do not crash on incorrect GLOBCNT range sent by client and send ecRpcFormat error value instead
* Reset synccontext when the sent cn is greater than expected to continue managing state properties
=> Enhance behaviour when receiving wrong GLOBCNT ranges

mapiproxy/libmapiproxy/openchangedb.c, pyopenchange/mapistore/pymapistore.c, python/openchange/provision.py, python/openchange/tests/test_provision.py, setup/openchange_provision
This means users will have to explicitly set *a* backend, whether it be ldb or mysql. 
I think this covers all code paths that deal with the default, but please let me know if there are others..
=> Remove default backend.

setup/openchange_provision
This option checks if the provision is possible. I added it because it is needed for Zentyal
server integration and I think it could be useful for more people.
If you do not find it useful, just clsoe the pull request and I will make a script
for Zentyal |server instead
=> Add check option to openchange_provision

mapiproxy/dcesrv_mapiproxy.c, mapiproxy/libmapiproxy/dcesrv_mapiproxy_server.c
Change configuration defaults for mapiproxy to:
dcerpc_mapiproxy:server = true
dcerpc_mapiproxy:interfaces = exchange_emsmdb, exchange_nsp, exchange_ds_rfr
Users can still go back to the old defaults by explicitly setting:
dcerpc_mapiproxy:server = false
dcerpc_mapiproxy:interfaces =
This reduce the amount of changes users need to make to their configuration when setting up OpenChange.
=> Change configuration defaults for mapiproxy.

mapiproxy/libmapistore/backends/python/rest.py, mapiproxy/libmapistore/backends/python/sample.py, mapiproxy/libmapistore/mapistore_python.c, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, python/mock/rest/api_server.py
This PR allows the modify_recipients and get_message_data functions in mapistore_python.c to process recipients with properties that aren't set. Thus, recipients in the REST API backend don't necessarily have the same set of properties (which was assumed before), so the code has been modified consequently.
=> [mapistore-python]: Allow NULL properties in recipients

mapiproxy/libmapistore/backends/python/rest.py
This PR implements different relational operations used in restrictions, such as `NotEqual`, `LessThan`, etc. It doesn't implement the DL membership operator. Comparisons are made in a Pythonic way and types are not checked.
The PR also includes a small corrections that uses the wrapping function for decoding data from the REST calls in FAI message retrieval.
=> Relational operators in Table implementation

mapiproxy/libmapistore/mapistore.h, mapiproxy/libmapistore/mapistore_interface.c, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcfold.c, mapiproxy/servers/default/emsmdb/oxcmsg.c
From `enum mapistore_error` to `enum MAPISTATUS`.
Added an utility function to map MAPISTATUS to the mapistore_error as well to try to keep real error code available.
Fixed use case: 
Opening a shared calendar with no permissions returns MAPI_E_NO_ACCESS instead of MAPI_E_NOT_FOUND making work when the shared calendar access is later granted.
=> Fix returned value from `emsmdbp_object_open_folder_by_fid`

mapiproxy/dcesrv_mapiproxy.h, mapiproxy/dcesrv_mapiproxy_unused.c, mapiproxy/libmapiproxy/backends/openchangedb_mysql.c, mapiproxy/libmapistore/backends/indexing_mysql.c, mapiproxy/libmapistore/backends/namedprops_mysql.c, mapiproxy/libmapistore/mapistore_backend.c, utils/backup/openchangebackup.h
This is another step towards being able to build without Samba installed.
=> Stop including samba_util.h.

mapiproxy/libmapiproxy/backends/openchangedb_mysql.c, testsuite/libmapiproxy/openchangedb.c
Now a new change number was being generated and the given one was ignored.
=> openchangedb: create_folder must use the given change number

mapiproxy/libmapistore/mapistore_interface.c, mapiproxy/servers/default/emsmdb/emsmdbp_object.c
Limited only to cached mode as the properties are copied in oxcfxics
(RopSyncImportHierarchyChange).
Now the backend can receive a NULL as target folder on move folder
operation (mapistore_folder_move_folder), this means it is moved
to be a root folder.
=> Implement moving a mapistore folder to a root folder

mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/emsmdbp_provisioning.c, mapiproxy/servers/default/emsmdb/oxcfold.c, mapiproxy/servers/default/emsmdb/oxcfxics.c, mapiproxy/servers/default/emsmdb/oxcprpt.c, mapiproxy/servers/default/emsmdb/oxomsg.c
As suggested by @blaxter and @jelmer to avoid creating two
talloc contexts where is not required to create a temporary
context.
=> Use talloc_new instead of talloc_zero(NULL, TALLOC_CTX)

mapiproxy/servers/default/emsmdb/emsmdbp_object.c
* If a stream was open, the size of the buffer was set to the size of the existing property. Therefore, writing a stream of a different size resulted in partially overwriting the previous value of the property.
* This fixes the "weird HTML body" bug when sending from _Drafts_ in the REST API
=> Allow WriteStream operation with different lengths

libmapi/conf/mapi-named-properties
It is PtypMultipleString (0x101F) Unicode and not String 8b
according to [MS-OXPROPS] Section 2.444
=> Fix prop type for PidNameKeywords

exchange.idl, libexchange2ical/exchange2ical.c, libexchange2ical/exchange2ical_property.c, libmapi++/src/folder.cpp, libmapi++/src/message.cpp, libmapi/IMAPITable.c, libmapi/libmapi.h, libmapi/simple_mapi.c, libocpf/ocpf_public.c, mapiproxy/servers/default/emsmdb/oxctabl.c, utils/backup/openchangemapidump.c, utils/exchange2mbox.c, utils/mapitest/mapitest_common.c, utils/mapitest/module.c, utils/mapitest/modules/module_oxcfold.c, utils/mapitest/modules/module_oxcmsg.c, utils/mapitest/modules/module_oxcperm.c, utils/mapitest/modules/module_oxctable.c, utils/mapitest/modules/module_zentyal.c, utils/openchangeclient.c, utils/openchangepfadmin.c
Instead of crashing.
And we have implemented in libmapi for MAPI clients:
* Give support to set read direction on QueryRows oxctabl in libmapi
* Current limitation: Read backwards from BOOKMARK_BEGINNING will always return the first row. MAPI clients should check Origin response field to know nothing else to read. Current `libmapi:QueryRows` does not support it.
=> Implement read backwards on a oxctabl in QueryRows ROP

CHANGES.md, mapiproxy/servers/default/emsmdb/emsmdbp.c, mapiproxy/servers/default/nspi/emsabp.c
There is no need to create a new one for each bound session. So now all nspi and emsmdb session will use the same ldb_context. This will fix a problem (when `dcerpc_mapiproxy:samdb_url` is defined and not local) of too many ldap connection opened.
Also in case the samdb is not local (`dcerpc_mapiproxy:samdb_url` defined) the samdb context is open with reconnect flag.
I'm also introducing a new **CHANGES.md** file which should include for now on (if we see is useful) the new changes from an user perspective.
=> mapiproxy: single samdb connection

mapiproxy/servers/default/emsmdb/emsmdbp.c, mapiproxy/servers/default/nspi/emsabp.c
Fix ad02428d3b504380e6ddb90df242e1ff537048ca where samdb connections were changed to have only one. We cannot use the memory context of the emsmdb/nspi session but use a global one so they won't be released until the end.
=> mapiproxy: do not release samdb connection

mapiproxy/servers/default/emsmdb/emsmdbp.c, mapiproxy/servers/default/nspi/emsabp.c
Fixes 9519a9e227dae8d1de70705313c5a72517c99574 tevent needs also to have the global autofree memory context
=> mapiproxy: do not release samdb connection, tevent

CHANGES.md, mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.h, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcfxics.c, mapiproxy/servers/default/emsmdb/oxomsg.c
Furthermore, a shared root folder properties managed by OpenChange DB can be read on behalf of other users.
It creates a XML attachment on RopTransportSend following [MS-OXSHRMSG] spec
for the format by reading Sharing Object properties defined in [MS-OXSHARE]
when the class of the message is "IPM.Sharing".
It sends to the mapistore backend, the three relevant properties for the attachment:
* The long filename
* The binary data (XML string in UTF8)
* The MIME tag
In addition to this, it asks to the mapistore backend the additional sharing properties on cached mode when the message has `IPM.Sharing` as `PidTagMessageClass`.
=> Give support to calendar sharing invitation

exchange.idl, ndr_mapi.c
With these changes MAPIProxy proxies traffic without the need for the downgrade module.  The actual ROPs in EcDoRpcExt2's ROP request payload are not decoded yet.
=> Ensure MAPIProxy handles EcDoConnectEx/EcDoRpcExt2

exchange.idl, libmapi/libmapi.h, libmapi/nspi.c, mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c, utils/mapitest/modules/module_nspi.c, utils/mapitest/modules/module_zentyal.c
Also added to NSPI methods the codepage check mandated by specifications
The NSPI UpdateStat and QueryRow method are called when browsing the entries in the address book before they failed in their implemntation and if you had more of 40 entries it dont worked correctly.
=> Fixed NSPI UpdateStat and QueryRows methods

script/debugoc.py
Useful to run it from a wrapper script with a list of dirs as commandline args.
=> Optional pass of source dirs to gdb in debugoc.py

script/openchange_user_cleanup.py
We can have both `imap://host:port` and `host:port` on sogo config so the regex should have the scheme as an optional match.
=> openchange_user_cleanup: parse imap config properly

mapiproxy/dcesrv_mapiproxy.c
This is mostly a RFC; this change depends on a matching change in Samba.
See https://lists.samba.org/archive/samba-technical/2014-November/103935.html
=> Add hook to set 'dcerpc endpoint servers' by default.

mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c
This is necessary because Outlook 2010 sometime send a NSPI QueryRow where
the initial position is after the end of the table. For example,
using the search in the GAL.
If I interpret the requested delta as going backwards, the client behavior
is fine so I suspect in a sign error in the client side.
=> nspi: QueryRows now can accept a NumPos bigger or equal to table size.

libmapi/libmapi.h, libmapi/property.c, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcmsg.c
* Refactor fill_prop_index to reuse as much code as possible
* We have two new functions in libmapi to extract the email address value and display name value from a SPropTagArray checking a set of properties. This avoids duplications and is safer.
* Added checks on returned values on copying msg recipients
=> Several fixes on copy message recipients

CHANGES.md, mapiproxy/servers/default/emsmdb/emsmdbp_object.c
Using PidLidSharingLocalType property.
Not available in any spec but tested empirically.
It requires #244 to work.
=> Sharing request and invitation for other types of folders

exchange.idl
Windows doesn't make these interfaces available over ncacn_np either,
and this will make it significantly easier to create a standalone openchange daemon.
=> Remove ncacn_np from OpenChange DCE/RPC endpoints.

python/openchange/provision.py
The provision process compares the dns_owner with the fqdn to check
if the directory is local or resides in another controller.
Since the check is with DNS names it should be case insensitive.
=> provision: Make dns_onwner comparation case insensitive

mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c, mapiproxy/servers/default/nspi/emsabp.c
emsabp.c:
Make emsabp_search return ordered list of MIDs
It was assumed that this method returned the MIDs ordered like emsabp_ab_container_enum.    This made the dcesrv_NspiSeekEntries return a bad position.
After this change the MIDs are ordered by the SortType in the pStat paremeter.
Currently only SortTypeDisplayName is fully supported, SortTypePhoneticDisplayName return error and other values are unrecognized and default to not sort.
dcesrv_exchange_nsp.c:
- Query rows now calculates the position in the table instead of trusting in the  NumPos field of the pStat input parameter
- QueryRows do not return error when applying the delta makes a position overflow, instead return rows until the end of the table is reached
- QueryRows do not return error when a negative delta makes a …
=> Fixed NSPI's QueryRows and SeekEntries calls

script/bug-analysis/apport-config.backup/Ubuntu 14.04/sources.list, script/bug-analysis/apport-config.proposed/Ubuntu 14.04/sources.list, script/bug-analysis/apport-config/Ubuntu 14.04/sources.list
Please @sixstone-qq review this it shouldn't had problems but just in case. I'm maintaining the proposed up to update just in case we start using that repo again. Additionally I added two "old" repos to maintain the differences between 4.0 and 4., It shouldn't cause problems right?
=> 4.1 is now the stable version for the bug-analysis tool

mapiproxy/servers/default/nspi/emsabp.c
In emsabp_ab_container_enum and emsabp_search the struct ldb_server_sort_control
was not initialized to zero.
This made that the inverse sort attribute was randomly set to non-zero, making
the address list to show with inverse order.
=> nspi: Initialize ldb_server_sort_control correctly to avoid inverse sort

Makefile, mapiproxy/libmapistore/mapistore.h, mapiproxy/libmapistore/mapistore_notification.c, mapiproxy/libmapistore/mapistore_notification.h, mapiproxy/libmapistore/mapistore_notification.idl, mapiproxy/libmapistore/mapistore_private.h, mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c, mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.h, mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.h, mapiproxy/servers/default/emsmdb/emsmdbp.c, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcnotif.c, mapiproxy/servers/default/emsmdb/oxctabl.c, testsuite/libmapistore/mapistore_notification.c, utils/ocnotify.c
Add API and unit test for the notification subscription model. This part of the API is used in emsmdb to emit subscription on events for which to be notified and consumed in asyncemsmdb.
=> Third iteration of the asynchronous emsmdb endpoint service

mapiproxy/libmapistore/mapistore_python.c
Relax float check as we json numbers do not match PyFloat exactly (an integer is not considered a valid pyfloat)
=> relax float check

utils/mapitest/modules/module_zentyal.c
NSPI table position functionality has been rewritten following
rules from MS-OXNSPI, in this case 3.1.4.5.1 describes absolute
positioning and NumPos value is not relevant but Delta field.
Long story short, this RoP should return MAPI_E_SUCCESS and that's
what happens now, so let's adjust the test to reality
=> mapitest: zentyal_1872 expects MAPI_E_SUCCESS

mapiproxy/libmapistore/mapistore_interface.c, mapiproxy/servers/default/emsmdb/oxcfold.c
mapistore_folder_open_folder expects a backend folder object and
not a emsmdbp object according to other calls.
This has been detected by running OXCFOLD-CREATEFOLDER mapitest.
=> Fix EmptyFolder ROP

mapiproxy/libmapistore/mapistore.h, mapiproxy/libmapistore/mapistore_indexing.c, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/emsmdbp_provisioning.c
This gives the possibility to set an indexing record with
a given MAPIStore URI without asking the backend to get
this URI as it is already set by OpenChange level.
This specially applies to special folders on provisioning
but also on creation of MAPIStore root folders.
=> Introduce mapistore_indexing_record_add_fmid_for_uri

utils/mapitest/modules/module_oxcfold.c
The objects were not released on failure.
=> [mapitest] Fix mapi object management in OXCFOLD-MOVEFOLDER

libmapi/IMAPIFolder.c, mapiproxy/libmapistore/mapistore.h, mapiproxy/libmapistore/mapistore_interface.c, mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.h, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcfold.c, utils/mapitest/module.c, utils/mapitest/modules/module_oxcfold.c
* It honors the HARD_DELETE flag as described.
Another things done in this PR:
* libmapi: Give support to not send any flag
* Delete mapistore first on mapistore root folders
* As this honors when it is unable to delete due to flags
* Added new mapitest to test DeleteFolder ROP flags
* Tested against OpenChange and Exchange 2010
=> Update indexing entries when deleting a folder

mapiproxy/libmapistore/backends/indexing_mysql.c, script/openchange_user_cleanup.py
* Assume Memcached keys can be missing (falling back to MySQL in that case) instead of relying on them.
* Include a cleanup of Memcached in the user cleanup script. This will flush the Memcached keys of other users that are logged in, but this won't cause OpenChange crash anymore.
The code in this PR is by @blaxter, excepting a couple minor corrections in some parentheses to fit the `OC_DEBUG` macro and a return value.
=> Ignore Memcached errors and fall back to MySQL

.travis.yml, testprogs/blackbox/test_openchangeclient.py
testtools is no longer used or installed by Samba.
=> Remove dependency on testtools.

configure.ac
Avoid linking problem with 1.0.8 on Ubuntu trusty
=> Upgrade libmemcached requirement to 1.0.18 to avoid memcached_exist issue

CHANGES.md, mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.h, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcfold.c, mapiproxy/servers/default/emsmdb/oxcfxics.c, utils/mapitest/module.c, utils/mapitest/modules/module_oxcfold.c
This happens on online mode and on the creation of special
folders such Sync Issues during first logon.
The implementation does the following:
* Create the folder using Fallback role (as we don't have more information)
* Replace the folder with the correct role once the first
SetProps operation is done
We have added a new mapitest to test this specific path implemented
during first logon by Outlook.
This also fixes other mapitests from OXCFOLD testsuite. See the current status:
```
[STAT] FAILED TEST CASES
* OXCFOLD                            : OXCFOLD-MOVECOPY-MESSAGES (Unexpected Fail)
* OXCFOLD                            : OXCFOLD-HARDDELETEMESSAGES (Unexpected Fail)
* OXCFOLD                            : OXCFOLD-HARDDELETEMESSAGESANDSUBFOLDERS (Unexpected Fail) …
```
=> Fix creation of root folders using CreateFolder ROP

mapiproxy/libmapistore/mapistore_notification.c, testsuite/libmapistore/mapistore_notification.c
Fix case where case in Active Directory is different from the one querying the resolver service
=> [oxcnotif] make resolver cn case insensitive

property.idl
Although these changes don't produce any visible behaviour change, they fix a typo in the TZRule flag definitions. The specification can be found in [MS-OXOCAL] 2.2.1.41.1
=> [oxocal] Fix TZRule flags

script/mkversion.sh, utils/mapitest/mapitest_print.c
Including this information prevents openchange's build from being
reproducible.
Build-time kernel information is also of limited value,
as the kernel OpenChange is built on is likely different from the
kernel it is run on.
See also https://wiki.debian.org/ReproducibleBuilds/About
=> Drop kernel information from version header and mapitest.

CHANGES.md, mapiproxy/libmapiproxy/backends/openchangedb_backends.h, mapiproxy/libmapiproxy/backends/openchangedb_ldb.c, mapiproxy/libmapiproxy/backends/openchangedb_logger.c, mapiproxy/libmapiproxy/backends/openchangedb_mysql.c, mapiproxy/libmapiproxy/libmapiproxy.h, mapiproxy/libmapiproxy/openchangedb.c, mapiproxy/servers/default/emsmdb/emsmdbp_provisioning.c, mapiproxy/util/mysql.c, testsuite/libmapiproxy/openchangedb.c
This is a tentative fix for Deleted Items (1) duplicated folders...
It also adds the following low level changes:
* Add `set_system_idx` call to a OpenChangeDB folder
* Fix on getting unsigned long long from a NULL string
=> Reuse a folder as special folder if one already exists on Logon

mapiproxy/servers/default/emsmdb/emsmdbp_provisioning.c
This fixes a regression introduced by 63f2136a when
we want to reuse a folder as special folder if one
already exists on Logon.
Without this patch, the client gets messed up because
the fid set is not corresponding to the right folder,
making appear MAPI_E_NOT_FOUND opening folders and
incongruent information in oxcfxics protocol when
hierarchy was synched.
An example was the creation the Calendar, Contacts
and Tasks special folders by the client ignoring the
one we create on first Logon.
=> Refactor provision to use current_fid when it is set

CHANGES.md, Makefile, libmapi/libmapi.h, libmapi/libmapi_private.h, libmapi/mapi_object.h, libmapi/property.c, libmapi/simple_mapi.c, mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.h, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcfold.c, mapiproxy/servers/default/emsmdb/oxosfld.c, ndr_mapi.c, property.idl, testsuite/libmapi/mapi_property.c, utils/mapitest/module.c, utils/mapitest/modules/module_oxosfld.c
* On [MS-OXOSFLD] Section 3.1.4.1, where a CreateFolder ROP must not fail but reuse a fid if a special folder name is trying to be set.
* On [MS-OXCFOLD] Section 3.2.5.3, where a DeleteFolder ROP must fail with ecAccessDenied if the folder to delete is a special folder
This is done by adding a new function to check if a fid belongs to a special folder following [MS-OXOSFLD] 2.2.2 section. To do this is required to implement `PersistData` and `PersistElement` structures to parse and marshal in ndr. The latter has been tested with new unit tests.
For testing this new feature, a new module has been added and it is run with the following command:
```
$ bin/mapitest --mapi-calls=OXOSFLD-ALL
```
It requires to have this PR https://github.com/Zentyal/sogo/pull/131 ready if SOGo backend is used …
=> CreateFolder and DeleteFolder now matches [MS-OXOSFLD] spec

python/openchange/migration/directory.py, python/openchange/provision.py
According to [MS-OXCMAIL] Section 1.1, the primary
proxyAddresses entry is the SMTP one and the secondaries
proxyAddresses entries are the smtp ones.
This fixes a regression introduced in #240 in OOF support in Outlook 2007 as it was taking the secondary entry as primary to set OOF. As it is fixes a regression, no CHANGES are needed as the version is not yet published
=> Set postmaster proxyAddresses entry as secondary

mapiproxy/libmapistore/mapistore_python.c
This PR corrects the behaviour of `mapistore_python_message_set_read_flag`.
* The flags that the function takes define de behaviour of the function (set/clear read flag and send read receipt).
* The `PidTagMessageFlags` property is read and not overwritten.
* Read receipts are still unhandled after this PR.
=> Correct set_read_flag behaviour

CHANGES.md, mapiproxy/servers/default/emsmdb/oxcmsg.c
When the data blob had a layout, errors were being checked at the first byte instead of at the second one.
=> Fix property pull from data blobs in parse_ModifyRecipientRow

mapiproxy/libmapistore/mapistore_indexing.c
This avoids return MAPI_E_INVALID_PARAMETER when the connection
to the database is not done for the given user.
It mimetise other procedures in the file such as
`mapistore_indexing_record_add_fmid`.
=> indexing: ensure DB connection on allocating fid operation

CHANGES.md, exchange.idl, libmapi/nspi.c, mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c, mapiproxy/servers/default/nspi/emsabp.c
By complying a little more the spec from [MS-OXNSPI].
Namely, we have followed strictly which checks are required for every operation related with a `emsabp_search` and added some easy-to-add sanity checks. Check every individual commit for details on which server processing rule has been included in which operation.
With these fixes, no more `MAPI_E_INVALID_BOOKMARK` is returned on requesting opening a shared calendar from the address list.
=> Open a shared calendar from address list in Outlook 2013

python/openchange/migration/directory.py, python/openchange/provision.py
This completes changeset [e92b1a5b19] setting postmaster address
as secondary SMTP address for group accounts.
See https://github.com/openchange/openchange/pull/306 for details
=> Set postmaster proxyAddresses entry as secondary in groups

utils/mapitest/modules/module_zentyal.c
Although it can be not supported by the server, the specification
says nothing about updating STAT block with this SortType,
so we are not longer failing
=> mapitest: Success on NspiUpdateStat with SortTypePhoneticDisplayName

CHANGES.md, mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c
When building the MAPIStore SOGo URLs, the `username` part can be a mail
address. In that case, we need to replace the `'@'` character in it by
`"%40"`.
=> [oxcnotif] Support SOGo URLs with the mail address as username

python/openchange/migration/directory.py
The msExchRecipientTypeDetails and  msExchRecipientDiplayType
attributes should only be added to users with openchange enabled
otherwise we will get error later when enabling them.
=> Migration: add new attributes only to users with account enabled

utils/mapitest/mapitest_print.c, utils/mapitest/module.c, utils/mapitest/modules/module_oxcfxics.c
* Hierarchy synchronisation
* Over the parent folder to include data
* Download the configured Fast Transfer buffer
* Check the transfer is done (Fixed in #331)
* Parse the buffer to see it is correct
* Include Contents synchronisation
=> Improve mapitest over oxcfxics downloading

CHANGES.md, mapiproxy/servers/default/emsmdb/oxcfxics.c
By doing two changes:
* Perform the search for message identifiers along with the change number to discard a change whose is already included in the `cnset_seen` before opening the message and get all its available properties.
* Set sort order in changed messages before getting the table row count and conditionally
Use case:
No infinite loop with no full synced folder in Outlook 2013 when you were in the middle of the initial synchronisation in a business size folder.
=> Optimise fast transfer message change

mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c
Commit https://github.com/openchange/openchange/commit/58abea1386bfd932e29f531d7991b590f6c07ac9 introduced an error in how the URLs were built, so they worked in Zinc
but not in Zentyal server
=> oxcnotif: fix notification regression in zserver

mapiproxy/services/ocsmanager/ocsmanager/config/routing.py, mapiproxy/services/ocsmanager/ocsmanager/controllers/oab.py
Allow HEAD request, otherwise I'm getting sync issues and outlook won't download the (empty) oab.
=> ocsmanager: fix empty offline address book

CHANGES.md, mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.h, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcfxics.c, mapiproxy/servers/default/emsmdb/oxomsg.c
When Synchronizing Hierarchy of folders, TransferStatus was always
set to TransferPartial even if the transfer was completed. This commit
compares the position and length of the stream to determine if it is
over or not.
=> Fix hierarchy synchronization issues / Improve FastTransfer

CHANGES.md, mapiproxy/servers/default/emsmdb/emsmdbp_object.c, mapiproxy/servers/default/emsmdb/oxcfxics.c
And not with normal messages information in SyncGetTransferState ROP.
According to [MS-OXCFXICS] Section 2.2.1.1.3, the meta-property must
contain only information from FAI messages and the MetaTagCnsetSeen
has information from normal messages and folders depending on the type
of the synchronisation.
This ROP is used by the client to get the latest state of synchronisation
after uploading and it is used by subsequently calls to sync contents/hierarchy.
The most common use case that is fixed:
* Old mails are now synchronized after the account cleanup
Other sync issues in folders with FAI messages (INBOX) should have
less number of sync issues.
Along with the fix, I clean it up the code:
* Return error instead of aborting when it is not necessary
* Remove dead and incorrect code
* Add more …
=> oxcfxics: Fill MetaTagCnsetSeenFAI property only with FAI messages

mapiproxy/libmapiproxy/backends/openchangedb_logger.c
Avoid crashing on GetReceiveFolderTable ROP when
openchangedb_logger is set.
=> ocdb logger: Implement ReceiveFolderTable

python/openchange/provision.py, setup/openchange_provision
To ignore ldap errors when inserting new schemas.
Disabled by default but really useful in some scenarios.
=> Provision: add --ignore-already-exists option

utils/mapitest/mapitest.h, utils/mapitest/mapitest_stat.c, utils/mapitest/mapitest_suite.c, utils/mapitest/module.c
Check using a "hack" if the server is OpenChange and skip flagged tests accordingly.
Every commit belongs to a spec with the ROPs that are not implemented.
With this PR, now *\<SUITE\>-ALL* runs all tests from the suite even if it has some of them to be skipped.
=> Mapitest: Skip not implemented tests in OpenChange server

mapiproxy/libmapistore/mapistore_interface.c, mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c, mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.c
* Fixed crash in asyncemsmdb double free of mstore_ctx members because mapistore_release called twice (on unbind and as destructor).
* mapistore context destructor removed because is not needed: all their members are created inside the same memory context tree.
* Free both asyncemsmdb_session and emsmdb_session: they are now created within different memory context and freed when they are removed from our list of active sessions.
=> Free mapistore context and [async]emsmdb_sessions

mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c, mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.c
Partial revert of https://github.com/openchange/openchange/pull/347 (what fixes the crash there was the removal of `mapistore_release` call).
There is some issue with session handling that creates crashes if we release the session.
ps: I will look into this soon.
=> Workaround: Revert of release sessions

Makefile, libmapi/idset.c, testsuite/libmapi/mapi_idset.c, testsuite/testsuite.c, testsuite/testsuite.h
Added unit tests.
MetaTagIdsetDeleted used this scheme, for example.
See [MS-OXCFXICS] Section 2.2.2.4.1 for details.
=> oxcfxics: Support REPLID-based IDSET parsing

ndr_fasttransfer.c
It is REPLID-based and not REPLGUID-based IDSET.
It requires #350 to work.
=> ndr_fasttransfer: Proper decoding for MetaTagIdsetDeleted

python/openchange/provision.py, setup/openchange_group, setup/openchange_neworganization, setup/openchange_newuser
This PR contains:
1. Enable all groups option when provisioning organization
2. Allow to remove openchange attributes from a user
3. Users and groups can now be in any part of the LDAP tree, this removes special code for Zental server. Unfortunately the 'enable all groups' option is dependent on a specific location.
=> Provision all group and other provision fixes

python/openchange/migration/directory.py, python/openchange/provision.py
This attribute is needed to manage ActiveSync ACL per user.
Since this change is transparent to end-user there is no CHANGES.md line
=> provision: Added msExchOmaAdminWirelessEnable attribute to user

utils/mapitest/module.c, utils/mapitest/modules/module_zentyal.c
Additional non-mandatory property PidTagObjectType was treated
as mandatory in backend code. This test make sure no crash
is hit when only mandatory properties are sent for one recipient
and other one has some additional properties such as PidTagObjectType.
This is crashing using OpenChange + SOGo backend if https://github.com/Zentyal/sogo/pull/100 is applied and https://github.com/Zentyal/sogo/pull/154 is not.
=> mapitest: Add ModifyRecipients call that now crashes

python/openchange/migration/directory.py
The base dn of the first migration provision was too restrictive.
Depending on the naming schema this could trigger that old users
has not the msExchRecipientTypeDetails and msExchRecipientDisplayType
attributes added.
=> provision: Fixed first directory migration

libmapi/idset.c, testsuite/libmapi/mapi_idset.c
Now the REPLID-based parsing works with instances whose length is lower than 16B.
I've picked the sanity check on GLOBSET parser to have a IDSET without GLOBSET as valid parsed. It is required to have safer code while lowering the minimum length ceil.
=> oxcfxics: fix minimum length on parsing IDSETs

libmapi/idset.c, testsuite/libmapi/mapi_idset.c
When the last element in a range was being deleted, the higher element in the range was being increased instead of decreased, which produced a wrong final idset.
=> oxcfxics: Fix deletion of IDs within an idset

libmapi/simple_mapi.c, utils/mapitest/modules/module_oxcperm.c
By fixing a bug in client library:
* libmapi: Set PR_ENTRYID proptag on AddUserPermission oxcperm request
And making one of the tests independent from the users available in the server.
=> OXCPERM-ALL mapitest passes against OpenChange server

mapiproxy/libmapistore/backends/indexing_mysql.c
According to `mysql_record_get_fmid`, if a uri is indexed in
memcached, then the fmid is not deleted. But the `_memcached_setup`
method is populating the key/value store with deleted entries.
This fix makes sure only no soft deleted entries are in memcached
key/value store.
=> indexing: Do not setup deleted fmid in memcached

mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c
Stopping the server frees first the `asyncemsmdb_session` that calling
the `dcerpc_server_asyncemsmdb_unbind` to disconnect the current
dcerpc sessions. It *may* be because the `talloc_autofree_context` is called
before freeing the connections.
See this log:
```
mapiproxy/libmapistore/mapistore_interface.c:148(mapistore_release): freeing up mstore_ctx ref: 0x7f74cdc0b310
mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c:105(asyncemsmdb_mapistore_destructor): MAPIStore context released
mapiproxy/libmapistore/backends/namedprops_mysql.c:269(mapistore_namedprops_mysql_destructor): Destroying namedprops mysql context
mapiproxy/libmapistore/mapistore_interface.c:148(mapistore_release): freeing up mstore_ctx ref: 0x7f74cdbeb260 …
```
=> asyncemsmdb: Do not crash on stop

CHANGES.md, utils/openchangeclient.c
* Send `PidTagClientSubmitTime` while sending mail
* Send filename as unicode
* Send only available bytes while sending an attachment whose length is < 1024B
=> Several fixes on openchangeclient to send mails to OpenChange

mapiproxy/servers/default/emsmdb/oxcfxics.c
This check avoids a crash in the server when the Source Key can't be
retrieved, leaving the binary structure uninitialised.
This behaviour has been seen when there are MIDs in the database with a Replica ID that cannot
exist. This patch doesn't fix that bug, it just works the crash around.
=> Check return in oxcfxics_push_messageChange

exchange.idl, libmapi/libmapi.h, libmapi/property.c, mapiproxy/libmapistore/mapistore.h, mapiproxy/libmapistore/mapistore_backend.c, mapiproxy/libmapistore/mapistore_backend_defaults.c, mapiproxy/libmapistore/mapistore_interface.c, mapiproxy/libmapistore/mapistore_private.h, mapiproxy/servers/default/emsmdb/oxcfold.c, mapiproxy/servers/default/emsmdb/oxcfxics.c, ndr_mapi.c, testsuite/libmapi/mapi_property.c
* Cherry-pick the proper XID structure from @jkerihuel branch to decode FXBuffer.
* Implement helper function `get_SizedXidArray` to parse `PidTagPredecessorChangeList` property value in backend code
This is send back to backend code to manage the Predecessor Change List property value sent by the client to update accordingly and manage conflicts, if required.
This should be managed by OpenChange, but by now, it is leveraged to backends.
=> oxcfxics: pass predecessor change list to backend on MessageMove ROP

Makefile, config.mk.in, configure.ac, exchange.idl, exchange_debug.idl, libmapi/libmapi_private.h, ndr_fasttransfer.c, ndr_mapi.c, script/fxdump.py
- structured output for FX markers
- structured output for FX MetaTag
- colorized (ANSI color) output for FastTransferSourceGetBuffer
- print FILETIME into human readable dates
- print boolean values as 'True' and 'False' string
- ndr oriented function for dump_data which now dumps binary blob at ndr->depth
- decidated function to supply custom decoding for important properties (PidTagChangeKey, PidTagSourceKey, PidTagPredecessorChangeList)
- add exchange_debug interface and FastTransferSourceGetBuffer meta function to easily feed ndrdump with DATA_BLOB as an input
- add a convenient script (./script/fxdump.py) to turn hexadecimal output into binary blob to feed ndrdump using the exchange_debug interface
=> Advanced NDR decoder for FastTransferSourceGetBuffer response buffers

mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c
mstore_ctx has been talloc_steal by p, which is already been talloc_free(p)
=> asyncemsmdb: do not double free mstore_ctx

script/bug-analysis/README.md, script/bug-analysis/patches/packaging_impl.py
to patch packaging_impl.py from apport-retrace to retrace
packages properly from any version when the crash comes
from a Zentyal package.
=> Update README.md to notify developers of the requirement

mapiproxy/libmapiproxy/backends/openchangedb_mysql.c, mapiproxy/libmapistore/backends/indexing_mysql.c, testsuite/libmapiproxy/openchangedb.c, testsuite/libmapistore/mapistore_indexing.c
`mysql_affected_rows` is only reporting the affected rows and when the value has the desired value the number of affected rows is 0. We can change this behaviour by setting CLIENT_FOUND_ROWS
flag on mysql_real_connect but I'd prefer to have the MySQL connection as standard as possible and this case is not so often.
More details on the following link:
https://dev.mysql.com/doc/refman/5.5/en/mysql-affected-rows.html
This is affecting the following low level procedures:
* set_mapistore_URI
* set_system_idx
* update_fmid
=> Fix MySQL update check

mapiproxy/libmapistore/backends/indexing_mysql.c, mapiproxy/servers/default/emsmdb/oxcmsg.c
The analysis of the message identifiers involved in every crash
tends to highlight that the mid is initially garbage pushed to
the database and the fequency of this crash is statistically very
low ]1/5000;1/500000[. This patch therefore initializes messageID
to 0 beforehand and add memory checks to prevent data corruption.
At this stage of the investigation, this is the only plausible
explanation available. If it does fix the issue, then I expect
this fix to help narrowing it down even further.
=> Tentative fix for CR-1136.

mapiproxy/servers/default/emsmdb/oxcmsg.c
Previously the attachmentID was let initialized.
This error did not trigger any known failure because the PidTagAttachNumber
was latter assigned using the position in the attachment table.
=> emsmdb: Initialize attachmentID in attachment objects

CHANGES.md, mapiproxy/services/ocsmanager/ocsmanager/controllers/oof.py
Avoid encoding errors when settings and getting out of office state.
=> Out of office messages with non-ascii characters

mapiproxy/libmapiproxy/backends/openchangedb_logger.c, testsuite/libmapiproxy/openchangedb_logger.c, testsuite/libmapiproxy/openchangedb_multitenancy.c
* Implement missing unit tests for openchangedb_logger unittest.
* Avoid compilation warnings in openchangedb_multitenancy unittest + COPYRIGHT note
* Print out the change number returned value for `get_new_changeNumber` and `get_new_changeNumbers` for easing debugging purposes.
=> OpenChangeDB logger backend minor improvements + fixing compilation warnings

mapiproxy/services/web/rpcproxy/rpcproxy/channels.py
* Manage client disconnections waiting for CONN/B1 RTS packet 
* Check properly how to wait for IN channel from Outbound proxy
=> rpcproxy: Fixes on sad paths

libmapi/idset.c
It makes no sense to use log level 0 when no user will understand
that structure without reading the oxcfxics document. What I'm sure
not even all OC devs has read throughfully. :)
=> libmapi: IDSET_dump dumps to log level 5

ndr_fasttransfer.c
Concretely, the namedPropInfo element from [MS-OXCFXICS] Section 2.2.4.1
and, then, let the property value be parsed in the caller.
See the following output examples:
* 0x91C4000B (LID 0x00008229): 'True'
* 0x905A001F (Name "Content-Type"): 'message/rfc822'
=> fxdecoder: Decode named properties

ndr_fasttransfer.c
As specified by [MS-OXOSFLD] Section 2.2.6
Example Output:
PidTagFreeBusyEntryIds: ARRAY(4)
Null                     : SBinary cb=0
Delegate Information Object EntryID: SBinary cb=70
[0000] 00 00 00 00 DF 96 13 0F   7A D8 6C 42 91 00 42 6A   ........ z.lB..Bj
[0010] A6 B7 40 83 07 00 2C 10   FE 00 AB 98 5B 41 87 67   ..@...,. ....[A.g
[0020] 7A 93 3C 81 82 EC 00 00   00 00 04 03 00 00 2C 10   z.<..... ......,.
[0030] FE 00 AB 98 5B 41 87 67   7A 93 3C 81 82 EC 00 00   ....[A.g z.<.....
[0040] 00 01 04 0B 00 00                                   ......
Free/Busy Message EntryID: SBinary cb=0
Freebusy Data EntryID    : SBinary cb=46
[0000] 00 00 00 00 DF 96 13 0F   7A D8 6C 42 91 00 42 6A   ........ z.lB..Bj
[0010] A6 B7 40 83 01 00 2C 10   FE 00 AB 98 5B 41 87 67   ..@...,. ....[A.g
[0020] …
=> fxbuffer: Parse PidTagFreeBusyEntryIds for hierarchy changes

ndr_fasttransfer.c
Make it compliant with the model: error if < 0, otherwise success.
=> Fix error checking in the FastTransfer buffer parse.

CHANGES.md, mapiproxy/servers/default/nspi/emsabp_property.c
With this change the relephone and location field are shown in the
global address list.
=> nspi: added missing attributes mappings for telephone and location

mapiproxy/libmapistore/backends/namedprops_mysql.c
If the named_properties table is empty, the query
SELECT max(mappedId) FROM <table>
returns NULL, causing a crash in strtol() later.
Checking if row[0] is not NULL makes the code return MAPISTORE_ERR_DATABASE_OPS instead of crashing.
=> Fix crash caused by empty named_properties table
