libmapi/IMSProvider.c
libmapi/IProfAdmin.c
libmapi/mapi_profile.h
utils/mapiprofile.c

New option in mapi_profile (--roh-http-auth) to specify the HTTP
authentication scheme to use. Choose between 'basic' and 'ntlm'.

Merge last commit from Samuel Cabrero:

---

.travis.yml

This PPA already has the existing packages.

Use an openchange-owned PPA, so other people can also upload new packages.

---

libmapi/property.c
mapiproxy/libmapiproxy/fault_util.c
mapiproxy/libmapiproxy/fault_util.h
mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.c
mapiproxy/servers/default/emsmdb/emsmdbp_object.c
mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c
mapiproxy/servers/default/nspi/emsabp.c

Clean up the output of OC_ABORT and renamed to OC_PANIC, a bit more descriptive

fault_util: reformat and OC_ABORT --> OC_PANIC

---

doc/developer/standalone.txt

Initial developer doc for standalone OpenChange.

---

setup/openchange_newuser
setup/openchange_provision

Otherwise, as Jelmer Vernooij noticed, the triggered operation could be
a unexpected one.

Raise error when provision or newuser  commands are invoked with incompatible options

---

libmapi/libmapi.h
libmapi/libmapi_private.h
libocpf/ocpf_context.c
libocpf/ocpf_private.h
libocpf/ocpf_public.c
mapiproxy/dcesrv_mapiproxy.c
mapiproxy/libmapiproxy/dcesrv_mapiproxy_module.c
mapiproxy/libmapiproxy/dcesrv_mapiproxy_server.c
mapiproxy/libmapiproxy/libmapiproxy.h
mapiproxy/libmapistore/backends/indexing_tdb.c
mapiproxy/libmapistore/mapistore_backend.c
mapiproxy/libmapistore/mapistore_interface.c
mapiproxy/libmapistore/mapistore_notification.c
mapiproxy/libmapistore/mapistore_private.h
mapiproxy/libmapistore/mapistore_processing.c
mapiproxy/libmapistore/mapistore_replica_mapping.c
mapiproxy/libmapistore/mapistore_tdb_wrap.c
mapiproxy/libmapistore/mgmt/mapistore_mgmt.h
mapiproxy/modules/mpm_cache.h
testprogs/check_fasttransfer.c
utils/dlinklist.h
utils/mapitest/mapitest.c
utils/mapitest/mapitest_stat.c
utils/mapitest/mapitest_suite.c

This is a first step towards being able to build without having Samba installed.

Ship private copy of dlinklist.h from Samba.

---

doc/developer/logging.txt

Please comment, especially on the API.

Add suggested API for logging in OpenChange.

---

mapiproxy/servers/default/emsmdb/oxcfxics.c

Sort by PidTagMessageDeliveryTime descending order. 
Most recent delivery time first when available.

oxcfxics: latest messages first when syncing

---

.travis.yml
CHANGES.md
Makefile
README.smbconf.md
config.mk.in
configure.ac
mapiproxy/libmapistore.pc.in
mapiproxy/libmapistore/backends/indexing_mysql.c
mapiproxy/libmapistore/mapistore.h
mapiproxy/libmapistore/mapistore_indexing.c
mapiproxy/libmapistore/mapistore_interface.c

Solve scalability and performance issue when importing business size mailbox

mapistore: implement fmid cache with memcached

---

CHANGES.md
mapiproxy/servers/default/emsmdb/emsmdbp_object.c
mapiproxy/servers/default/emsmdb/oxcfxics.c

oxcfxics: Fix `Mark All as Read` feature regression bug

---

mapiproxy/servers/default/emsmdb/oxcfxics.c
mapiproxy/servers/default/emsmdb/oxomsg.c

* Proper spec document referenced in several ROPs
* Added a note to not implement part of the spec until a mapistore backend
implement the property

Several development documentation fixes

---

mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c

Regression on #208 I read so many times that pull request but I miss this, the only real change is  4f6be72

nspi: update stat fix

---

CHANGES.md
mapiproxy/libmapistore/mapistore.h
mapiproxy/servers/default/emsmdb/emsmdbp_object.c

It features the creation of XML for flavours of sharing according to [MS-OXSHARE] and [MS-OXSHRMSG] specification:
* Request to see personal calendar folder
* Accept/Deny this request
* Request + Invitation to see personal calendar folder

Calendar sharing request among different Outlook versions

---

mapiproxy/libmapistore/mapistore.h
mapiproxy/servers/default/emsmdb/emsmdbp_object.c
property.idl

Use property.idl to store property values

---

Makefile
mapiproxy/libmapistore/mapistore.h
mapiproxy/libmapistore/mapistore_errors.h
mapiproxy/libmapistore/mapistore_interface.c
mapiproxy/libmapistore/mapistore_notification.c
mapiproxy/libmapistore/mapistore_notification.h
mapiproxy/libmapistore/mapistore_notification.idl
mapiproxy/libmapistore/mapistore_private.h
testsuite/README.md
testsuite/libmapistore/mapistore_notification.c
testsuite/testsuite.c
testsuite/testsuite.h

mapistore interface + IDL + unit test
:hand: no review required :angel:  - only one iteration of my work in progress in jkerihuel/asynchronous-notifications branch

merging mapistore notification session management

---

Makefile
configure.ac
mapiproxy/dcesrv_mapiproxy.c
mapiproxy/libmapistore/mapistore.h
mapiproxy/libmapistore/mapistore_notification.c
mapiproxy/libmapistore/mapistore_notification.h
mapiproxy/libmapistore/mapistore_notification.idl
mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c
mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.h
mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.c
mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c
testsuite/libmapistore/mapistore_notification.c
utils/ocnotify.c

:hand: no review required :angel: - only one iteration of my work in progress in jkerihuel/asynchronous-notifications branch

merging mapistore notification resolver API

---

Makefile
mapiproxy/libmapistore/mapistore_notification.idl
mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.c
mapiproxy/servers/default/asyncemsmdb/dcesrv_asyncemsmdb.h
mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.c
mapiproxy/servers/default/emsmdb/oxctabl.c

Dispatch newmail + tablemodified notification to Outlook clients upon new email arrival

Fourth iteration of asynchronous emsmdb endpoint service

---

CHANGES.md
mapiproxy/servers/default/nspi/dcesrv_exchange_nsp.c

- Improve ANR search to look on more fields and match at the beginning of the string
- Use common code for both ResolveName and ResolveNameW functions
- Added some missing sanity checks

[nspi] Better ResolveName(W) search

---

Makefile
mapiproxy/servers/default/nspi/emsabp.c
mapiproxy/servers/default/nspi/emsabp_property.c
python/openchange/mailbox.py
python/openchange/migration/__init__.py
python/openchange/migration/directory.py
python/openchange/migration/indexing.py
python/openchange/migration/named_properties.py
python/openchange/migration/openchangedb.py
python/openchange/provision.py
python/openchange/tests/test_migration.py
setup/AD/oc_provision_schema_attributes.ldif
setup/AD/oc_provision_schema_modify.ldif
setup/openchange_group
setup/openchange_migrate
setup/openchange_newuser

- Groups appear now in addresses list
- Added directory attributes to change icons from groups in addresses lists
- Added openchange_group command to enable groups for openchange
- Added needed migration from directory attributes
However the groups need this patch to be actually be able to receive mail https://github.com/Zentyal/sogo/pull/100

Added NSPI support for group accounts

---

mapiproxy/dcesrv_mapiproxy.c

Fix version check.

---

mapiproxy/servers/default/emsmdb/dcesrv_exchange_emsmdb.c
testsuite/libmapistore/mapistore_notification.c

and return ecRejected if asyncemsmdb to mimic previous behavior

[oxcnotif] Fix Outlook disconnection when asyncemsmdb is missing

---

testsuite/README.md

Following 4e87318 commit which allow this to be set.

Add paragraph to explain how to see which unit tests are run

---

CHANGES.md
script/sogo_indexing.py

Add script to offload indexing process

---

mapiproxy/services/plugins/dovecot/openchange-plugin.c

When sending a mail to several recipients, Dovecot uses the `copy`
operation for the first recipient, then it uses the `save` one (which wasn't
implemented) for the rest of the recipients.
The main purpose of these two functions is initialising the `msg` variable,
so a wrapper function has been created. A couple of lines from the
`openchange_mail_copy` function have been removed after checking they
don't make an impact neither over LMTP nor LDA.

oxcnotif: Implement openchange_mail_save in notification plugin

---

script/bug-analysis/buganalysis/analysis.py

After adding a new server it is good to have right categorised.
There are some crashes uncategorised that can be done right with this patch.

retrace: Added asyncemsmdb component

---

mapiproxy/servers/default/emsmdb/oxcfxics.c
testsuite/libmapi/mapi_idset.c

And add unit tests to `IDSET_includes_guid_glob` function.

Include in IdsetDeleted only ids present in IdsetGiven

---

mapiproxy/servers/default/emsmdb/oxcfxics.c

Without it, the messages that are valid in the server that
the client must have the latest version are not included
in the initial IdSetGiven are returned back in the meta property.
This avoids sync issues in INBOX folder, which stops syncing, after
performing several movements at once. Although the bug is not
easy reproducible by hand, using automated tests, the bug was 100%
reproducible and with this commit is gone.
No update in `CHANGES.md` done as it is a regression from a previous unreleased change (Optimisation section).
PS: 5 weeks of several engineers to fix this.

oxcfxics: Always include valid mid in IdsetGiven

---

utils/mapitest/module.c

Explaining in a comment the reason because they are failing.
I could have expand the reason in separate commits, but I don't think it has any added value.

mapitest: Skip all tests failing in OpenChange

---

mapiproxy/services/web/rpcproxy/rpcproxy/channels.py

As specified by [MS-RPCH] Section 3.2.4.6, we must maintain the
connection alive and we can do it by sending ping messages.
We do, by now, sending 0.9 * Timeout sent to the client in CONN/A1 RTS PDU.

rpcproxy: Send Ping PDU to avoid timeout disconn in OUT channel

---

exchange.idl
ndr_fasttransfer.c

Add FX dump support for property PidTagAdditionalRenEntryIds

---

mapiproxy/servers/default/emsmdb/emsmdbp_object.c

The array of return values wasn't being updated for all the properties.
This, plus the lack of sanity checks, was leading to crashes when there
was an error retrieving a property.

Set return values in emsmdbp_object_get_properties_mapistore_root
